server:
  port: 9001

spring:
  application:
    name: user_service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # Eureka ????? ?????? ??? ????? ??? ???? ???? ??
    service-url:
      defaultZone : http://localhost:8761/eureka #127.0.0.1