server:
  port: ${SERVER_PORT} # 0으로 하면 랜덤으로 포트를 설정하겠다

spring:
  application:
    name: user_service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true # Eureka ????? ?????? ??? ????? ??? ???? ???? ??
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka #127.0.0.1 or localhost