server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service #first-service
          uri: lb://MY-FIRST-SERVICE #MY_FIRST_SERVICE 로 하면 500 에러..!!!
          predicates:
              - Path=/first-service/**
          filters:
  #            - AddRequestHeader=first_request, first_requests_header2
  #            - AddResponseHeader=first_response, first_response_header2
              - CustomFilter
        - id: second-service
          uri: lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
#            - AddRequestHeader=second_request, second_requests_header2
#            - AddResponseHeader=second_response, second_response_header2
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Gateway Logging Filter
                PreLogger: true
                PostLogger: true

      global-filter:
        load-balancer-client:
          enabled: true

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.cloud.netflix.eureka: DEBUG
#    org.springframework.cloud.loadbalancer: DEBUG